### ISSUE TITLE
Performance regression in version 2.2.1

### ISSUE THREAD

**Issue by StephanPirnbaum** [kontext-e/jqassistant-git-plugin#3]
With the update of the git scanner plugin, the scan time of a project increaed from around 37 seconds (version 2.1.0) to around 5:43 minutes (version 2.2.1).

The last two log lines before the scan hangs are:

    [INFO] Accepted Git project in <...>
    [INFO] No previously scanned repository was found, creating new node ...

If needed, I can provide an example.

**Comment by WilliamThimm** [comment]
Thank you for pointing that out. Version 2.2.2 should fix the issue. Based on my testing, the scan time should now be back to normal when the repository in question does not already exist in the Neo4j database (as seems to be the case for you). If you encounter any more issues, please feel free to reach out again!
