### ISSUE TITLE
Missing `Git:Repository`

### ISSUE THREAD

**Issue by JohT** [kontext-e/jqassistant-git-plugin#4]
The node `Git:Repository` seems to be missing in version 2.1.0. 
- There is no result when querying `MATCH (repo:Git:Repository) RETURN repo LIMIT 10`. 
- The following queries shows the count of all nodes with the label `Git` and also doesn't show a `Repository` label: `MATCH (git:Git) RETURN labels(git), count(*)`

In the newest version 2.2.1, however, there seems to be no problem with the Repository node. The scan then fails because of the [apostrophe error](https://github.com/kontext-e/jqassistant-git-plugin/issues/2).

## Context

- **Group-id:** de.kontext-e.jqassistant.plugin
- **Artifact-id:** jqassistant.plugin.git
- **Version:** 2.1.0
- **Java distribution:** adopt
- **Java version:** 17.0.12+7

## Reproduce

Either run jQAssistant with this git plugin on a clone of https://github.com/remix-run/react-router , or:
- Clone https://github.com/JohT/code-graph-analysis-pipeline
- Check the [prerequisites](https://github.com/JohT/code-graph-analysis-pipeline/blob/main/README.md#hammer_and_wrench-prerequisites), especially the environment variable `NEO4J_INITIAL_PASSWORD`.
- Edit [scripts/examples/analyzeReactRouter.sh](https://github.com/JohT/code-graph-analysis-pipeline/blob/main/scripts/examples/analyzeReactRouter.sh) and add the command line option `--explore` to the last line (analyze), which doesn't run any reports and lets you explore the Graph manually.
- Run [scripts/examples/analyzeReactRouter.sh](https://github.com/JohT/code-graph-analysis-pipeline/blob/main/scripts/examples/analyzeReactRouter.sh)
- Open http://localhost:7474/browser 
- Log in with the user `neo4j` and the password you have assigned to the environment variable `NEO4J_INITIAL_PASSWORD`.
- Query `MATCH (git:Git) RETURN labels(git), count(*)`

**Comment by WilliamThimm** [comment]
Version 2.2.2 fixes Issue #2, so you should now be able to use the latest version. The mentioned version also contains the `Git:Repository`-node again. Feel free to reach out again, if there are any issues left.

**Comment by JohT** [comment]
Thank you @WilliamThimm 👍.

While verifying #2 I must honestly admit that the missing `Git:Repository` node **was actually my fault**. I've [deleted it](https://github.com/JohT/code-graph-analysis-pipeline/blob/e5b7600122c84ccfefb6416debb7a6f4c24f108f/cypher/GitLog/Delete_plain_git_directory_file_nodes.cypher#L11) accidentally 🙈. 

**Background**
Analyzing the `.git` directory with jqassistant-git-plugin not only leads to `Git` nodes, but also includes `File` nodes for the contents in the directory. I was not able to exclude files in the `.git` directory most likely because of the following issue: https://github.com/jQAssistant/jqassistant/issues/410

Therefore, I wrote a [Cypher query that deletes the `.git` directory contents](https://github.com/JohT/code-graph-analysis-pipeline/blob/e5b7600122c84ccfefb6416debb7a6f4c24f108f/cypher/GitLog/Delete_plain_git_directory_file_nodes.cypher#L11). I've overseen that the `Git:Repository` is also a `File` node and is therefore also deleted 🙈.
